---


- name: Store cluster credentials
  awx.awx.credential:
    name: "cluster_{{ cluster_name }}"
    organization: rbohne
    state: absent
    credential_type: OpenShift Cluster v1

- name: Add host
  awx.awx.host:
    name: "{{ cluster_name }}"
    description: "Single Node"
    inventory: sno
    state: absent

- name: Create group for cluster
  awx.awx.group:
    state: absent
    name: "cluster_{{ cluster_name }}"
    description: "Cluster {{ cluster_name }} Group"
    inventory: sno