---


- name: Remove from ACM
  ansible.builtin.include_tasks: remove-from-acm.yml
  tags: acm

- name: Destroy VM
  ansible.builtin.include_tasks: destroy-vm.yml
  tags: vm

- name: Remove DNS records
  ansible.builtin.include_tasks: destroy-dns.yml
  tags: dns

# - name: Update AAP documentation
#   ansible.builtin.include_tasks: clean-aap.yml

- name: Destroy agent iso
  ansible.builtin.include_tasks: destroy-agent-iso.yml
  vars:
    ssh_public_key: "{{ lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY' ) }}"
  tags: agnet-iso
