---
- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
        name: "{{ cluster_name }}"

- name: Slurp kubeconfig
  ansible.builtin.slurp:
    src: "{{ openshift_install_dir }}/auth/kubeconfig"
  register: slurp_kubeconfig

- name: Create auto-import-secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: auto-import-secret
        namespace: "{{ cluster_name }}"
      stringData:
        autoImportRetry: "5"
        kubeconfig: "{{ slurp_kubeconfig['content'] | b64decode }}"
        server: "https://api.{{ cluster_name }}.{{ base_domain}}:6443"
      type: Opaque

- name: Create ManagedCluster
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: "{{ cluster_name }}"
        labels:
          cloud: auto-detect
          vendor: auto-detect
          cluster.open-cluster-management.io/clusterset: rbohne
      spec:
        hubAcceptsClient: true

